---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
  - name: webapp-port
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: webapp
  type: LoadBalancer